#!/bin/bash
# This hook is run after every virtualenv is activated.

# set the project environment based on folder
if [ -f "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME" ]; then
    typeset project_dir="$(cat "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME")";
    if [ ! -z "$project_dir" ]; then
        # Legacy projects may have a env.sh file
        env_file="$project_dir/env.sh";
        if [ -e "$env_file" ]; then
            source "$env_file";
        else
            echo "No project environment. Setting DEBUG=1";
            export DEBUG=1;
        fi
    fi
fi
